project:
  type: book
  output-dir: docs

book:
  title: "Duke Statistical Science Undergraduate Thesis Template"
  date: now
  reader-mode: true
  repo-url: https://github.com/DukeStatSci/dss-thesis
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - abstract.qmd
    - introduction.qmd
    - literaturereview.qmd
    - methodology.qmd
    - results.qmd
    - conclusion.qmd
    - appendix.qmd
    - references.qmd

format: 
  pdf: default
  html: 
    theme: cerulean
    mainfont: "Atkinson Hyperlegible"
    toc: true

editor: visual